### ISSUE TITLE
trying to open ZigZagBoomClone app/standalone blows up

### ISSUE THREAD

**Issue by farkerhaiku** [roaminggamer/CoronaGeek#1] opened 2015-04-05 15:52 UTC
When I open the standalone directory I get this exception on the mac client - Version 2015.2576 (2015.3.3) 

File: scripts/caseErrorDetect.lua
Line: 173
****\* WARNING! display.newImageRect() Image file: 'images/fillW.png' - does not exit.  Check case of file.

stack traceback:
    [C]: in function 'print'
    scripts/caseErrorDetect.lua:173: in function 'oldFunc'
    ssk/extensions/display.lua:88: in function 'newImageRect'
    scripts/oneTouch.lua:38: in function 'init'
    scripts/game.lua:48: in function 'init'
    main.lua:73: in main chunk

**Comment by farkerhaiku** [comment] 2015-04-05 15:55
also happens on old version 3/9, 3/16, and 3/23

**Comment by Lerg** [comment] 2015-04-05 16:58
Looks like filename casing issue.

Sergey

**Comment by roaminggamer** [comment] 2015-04-05 17:59
comment out the first two lines of main.lua

The 'caseErrorDetect' is malfunctioning on OS X.

I'll commit an update shortly.

-Ed

**Comment by roaminggamer** [comment] 2015-04-05 18:02
Committed.

**Comment by Lerg** [comment] 2015-04-05 18:06
Hi Ed, what is the problem on OS X? Have you figured out?

**Comment by roaminggamer** [comment] 2015-04-05 18:13
The problem is something to do with file permissions and lfs.  I think the
code that dives down in to sub-folders is failing.

I haven't had time to root cause the issue.  However, I'm sure I simply
made a mistake.

I do 99% of my work on my Windows machine, so I didn't see the problem pop
up.  Embarrassingly, I made an assumption that it would work there too.

-Ed

**Comment by roaminggamer** [comment] 2015-04-05 18:56
Looks like the problem is with Corona.

Run this on a Windows system and an OS X system,

print( system.pathForFile( "", system.ResourceDirectory ) )
- Windows - Prints folder where game code (main.lua, config.lua, etc.)
  is.
- OS X - Prints folder where Corona SDK binary is.

-Ed

**Comment by Lerg** [comment] 2015-04-05 19:16
Yeah, I remember now. You just have to use main.lua and remove last 8 characters.
print( system.pathForFile('main.lua', system.ResourceDirectory):sub(1, -9) )

**Comment by roaminggamer** [comment] 2015-04-06 02:33
Yep.  I'm going to make that change.  Meanwhile, I've filed a bug to see if
the Corona staff can fix it.

-Ed

**Closed as completed** 2016-01-18 22:10 UTC
